# Generated by Django 4.1.7 on 2023-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=16)),
            ],
        ),
    ]
